server:
  compression:
    enabled: true
  port: ${SIGU_SERVER_PORT:8080}
  error:
    whitelabel:
      enabled: false
  servlet:
    encoding:
      force: true

spring:
  application:
    name: sigu

  profiles:
    active: dev

  devtools:
    add-properties: false

  mvc:
    throw-exception-if-no-handler-found: true

  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: ${SIGU_DB_URL:jdbc:postgresql://localhost:5432/sigudb}
    username: ${SIGU_DB_USER:sigu}
    password: ${SIGU_DB_PASSWORD:secret}
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      # Hibernate Properties
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      #sla:
      #  http.server.requests: 50ms #DEPRECATED java.util.Map<String, org.springframework.boot.actuate.autoconfigure.metrics.ServiceLevelObjectiveBoundary[]>
    export:
      prometheus:
        enabled: true

problem:
  with-stack-traces: false

---

server:
  error:
    whitelabel:
      enabled: true

spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true

problem:
  with-stack-traces: true
